### ISSUE TITLE
Users are not receiving password reset emails

### ISSUE THREAD

**Issue by selmeci** [5of5/edgein-next#623]
# Description

We’ve had people complain about not receiving password reset emails.

## Task:
- [x] Investigate config in Aut0
- [x] Investigate the reset password process in the codebase
- [x] Fix identified problems

## Acceptance criteria

Emails with password reset are received in users' email boxes.
